version: "3.1"

services:
  # node:
  #   build: .
  #   ports:
  #     - "${PORT:-3000}:3000"
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:4
    ports:
      - "${DB_PORT:-27017}:27017"
